### ISSUE TITLE
Sync doesn't working - incorrect JSON format?

### ISSUE THREAD

**Issue by schopenhauer** [aykit/myownnotes-android#100]
Hello, I get the following error message with MyOwnNotes, when syncing my Notes app: "Not getting correct JSON from server. Server OK?"

For reference, my ownCloud instance 7.0.4 (stable) is running on Apache version 2.4.7, with Notes (app) version 0.9 installed. All SSL settings are working with an externally verified SSL certificate (Gandi). My phone has Android version 4.4.4 installed.

Any ideas, what this could be?

**Comment by ramschmaerchen** [comment]
Thanks for the input. This error normally occurs, when you installed the wrong owncloud notes app. However, as you are saying you have notes > 0.9 installed, it should work. Please activate the debug mode and paste output here. See https://github.com/aykit/myownnotes-android/blob/master/CONTRIBUTING.rst

**Comment by maltefiala** [comment]
As there was no more comment, I guess the problem was the wrong notes application. See #80.

**Comment by algogr** [comment]
I have the same problem with the last version of ownnotes. The server own notes app is 1.0

**Comment by maltefiala** [comment]
The server app is called notes. Someone funny decided to name his application own notes and caused a lot of confusion. Please ignore the trolls and install the right application: https://github.com/owncloud/notes/tree/1.0.0

**Comment by algogr** [comment]
Thank you very much for your answer. I 'll try it out
