### ISSUE TITLE
readme link to owncloud notes app is broken

### ISSUE THREAD

**Issue by ericfont** [aykit/myownnotes-android#101]
My server is setup, and this android app is installed, but I can't find the server backend notes app to install.  The link in your readme points me to https://apps.owncloud.com/content/show.php/Notes?content=160567 which is empty.

**Comment by ramschmaerchen** [comment]
Thanks for the hint. Notes seems to have been merged with core. You can find it here, install instructions included: https://github.com/owncloud/notes
