### ISSUE TITLE
Add support for sub directories

### ISSUE THREAD

**Issue by LudovicRousseau** [aykit/myownnotes-android#102]
I like to store my notes in different folders for different categories.

It is possible to create sub-folders in the Notes directory on OwnCloud Files application. But files present in the sub-folder are NOT visible to the Notes web application and also to the Android application.

Is it a by design choice to avoid sub directories?
If not, can it be added?

**Comment by ramschmaerchen** [comment]
My own notes is bound to the notes application. I myself like the minimal approach of notes. For me, subfolders would be over engineering. So no, we will not pursue this idea.
