### ISSUE TITLE
Problems with v8?

### ISSUE THREAD

**Issue by maltefiala** [aykit/myownnotes-android#111]
This one came in via mail:

> All I can say is: since the owncloud server moved from v7 to v8, the app says "wrong json format. Is the > server ok ?".
> The app is up to date (V1.5).
> My android version is 4.4.4 (Motorola)

**Comment by makesmile90** [comment]
Same problem for me.
Owncloud 8
MyOwnNote 1.5
Android 5.1.1

**Comment by maltefiala** [comment]
Did you install Notes? https://github.com/owncloud/notes

**Comment by maltefiala** [comment]
I am guessing you installed the wrong notes application. See #80. Closing this one for now.
