### ISSUE TITLE
Error: the url you requested data from doesn't seem to exist.

### ISSUE THREAD

**Issue by giovi321** [aykit/myownnotes-android#112]
I get the following error on one server which is identical to another server. Even the domain is the same, except that the one that gets the error has the number "2" at the end of the domain name.
Both the servers (either the working and the non-working one) are running owncloud 8.0.3 and notes 1.0.0. App version is 1.5

"The url you requested data from doesn't seem to exist. Check spelling or your internet-connection."

**Comment by giovi321** [comment]
Problem solved. The Common Name of the certificate of the server HAS to match the domain name (or ip) of the server.

**Comment by ramschmaerchen** [comment]
Dear @giovi321 , more info on how Android deals with TLS requests is available here: https://developer.android.com/training/articles/security-ssl.html

> One reason this [Hostname 'example.com' was not verified] can happen is due to a server configuration error. The server is configured with a certificate that does not have a subject or subject alternative name fields that match the server you are trying to reach. It is possible to have one certificate be used with many different servers. For example, looking at the google.com certificate with openssl s_client -connect google.com:443 | openssl x509 -text you can see that a subject that supports *.google.com but also subject alternative names for *.youtube.com, *.android.com, and others. The error occurs only when the server name you are connecting to isn't listed by the certificate as acceptable.

Basic information about SNI: https://en.wikipedia.org/wiki/Server_Name_Indication
