### ISSUE TITLE
JSON invalid

### ISSUE THREAD

**Issue by ghost** [aykit/myownnotes-android#80]
When the app tries to sync, it pop up an error saying "Invalid JSON format, is your server OK?" (Translated from French).

The app refuses to sync.

**Comment by LudovicRousseau** [comment]
@steppenhahn The link you gave https://apps.owncloud.com/content/show.php/Notes?content=160567 do not work any more "Content not found".

What is the Notes app I should use on the owncloud server? Does it still exist?

**Comment by ramschmaerchen** [comment]
Notes has been merged to core: https://github.com/owncloud/notes

**Comment by LudovicRousseau** [comment]
I have owncloud version 7.0.4 (Debian package) and the Notes application is not provided :-(

**Comment by ramschmaerchen** [comment]
Please follow the installation guide in the Readme of https://github.com/owncloud/notes

**Comment by LudovicRousseau** [comment]
@ramschmaerchen Thanks a lot. It works now.

**Comment by ramschmaerchen** [comment]
Great!
